resolver: lts-14.27
packages:
- .
extra-deps:
- fgl-visualize-0.1.0.1
- dotgen-0.4.2
- jvm-binary-0.9.0
- dirtree-0.1.3
- git: https://github.com/ucla-pls/jvmhs.git
  commit: 5f81a4aa0d982f56ef95135e1ab62495d51b9f9e
- git: https://github.com/ucla-pls/reduce.git
  commit: 8df6ccb65d2bc22af9135d80113097217db3cf7b
  subdirs:
    - reduce
    - reduce-util
flags: {}
extra-package-dbs:
build:
  library-profiling: true
  executable-profiling: true
